### ISSUE TITLE
Secret generation hangs on machines with close to no entropy

### ISSUE THREAD

**Issue by eskatos** [werval/werval#231]
This can happen in virtual machines / clouds instances.
This has been observed on Digital Ocean and reported by @jcdominguez.

```
user@host$ gradle devshell
>> Werval DevShell for werval-gradle starting...
Isolating worlds...
Starting isolated Werval Application...
Application has no 'app.secret', generating a random one for development mode!
> Building 85% > :devshell
```

and

```
user@host$ gradle secret
:secret
>> Generate new Werval Application Secret
> Building 0% > :secret
```

Thats because we require a secure source of entropy when generating new secrets.
And in fact, if one wants good entropy he has to wait for it.

Secret generation occur when
1. one wants to generate a proper production secret
2. unit tests with no secret defined in configuration
3. development mode with no secret defined in configuration

For `1` there's nothing to do except use a system with enough entropy.
For `2` and `3` we could generate the temporary secrets with a loosy entropy. They are temporary after all. The only benefit would be allowing running tests and dev mode in badly setup cloud VMs. Could prove usefull for some CI systems for example.

**Comment by jcdominguez** [comment]
Workaround for Digital Ocean Ubuntu Droplets:
install haveged

See: 
https://www.digitalocean.com/community/tutorials/how-to-setup-additional-entropy-for-cloud-servers-using-haveged

**Comment by eskatos** [comment]
Thanks @jcdominguez.
Looks like [haveged](http://www.issihosts.com/haveged/) is packaged for most of the linux distributions, good.
